public void invoke(){
	try{
		TestExceptionHandler.runTry();
	}
	catch(Exception e){
		TestExceptionHandler.runCatch();
	}
}